DIRECTORY:
  dataset: /DATA/train.csv

SEED:
  random_seed: 42

DATALOADER:
  val_size: 0.05
  num_workers: 4
  shuffle: True 
  pin_memory: 4
  drop_last: False
  n_split: 10

TRAIN:
  tree_method: exact
  learning_rate: 0.05
  max_depth: 10
  subsample: 0.5
  min_child_weight: 50
  colsample_bynode: 0.5

TRAIN2:
  tree_method: hist
  learning_rate: 0.07
  max_depth: 16
  subsample: 0.5
  min_child_weight: 60
  colsample_bynode: 0.5

COLUMNS:
  id: index

  preprocess: True

  cols:
    - height
    - weight
    - age
    - locationcancer
    - cancerimagingT
    - cancerimagingN
    - cancerimagingM
    - classificationcancer
    - surgicalcancerT
    - surgicalcancerN
    - surgicalcancerM
    - boundarysurgical
    - surgicalmethod
    - totaldose
    - radiationcnt
    - radiationperdose
    - treatmethod
    - treatech
    - sex
    - bp
    - bs
    - sm
    - familyhistory
    - relapse
    - involvementrenal
    - lymphrenal
    - egfr
    - ros1
    - alk

LABEL_ENCODING:
  N: 0.0 # NO
  Y: 1.0 # YES
  M: 0.0 # MALE
  F: 1.0 # FEMALE